### PR TITLE
Allow to encode Config

### PR DESCRIPTION
**Pull request by zetok**

### CODE REVIEW

**Comment by aatxe** [comment]
Is there a desired use case for this? It was originally left out intentionally because I didn't see a reason for a bot to be able to modify its configuration. I suppose one application would be writing some sort of configuration generation tool. Do you have anything in mind?

**Comment by zetok** [comment]
Yes.
Bot checks whether .json config exists - if it does, it loads its, if it doesn't, it uses hardcoded defaults to write config.

**Comment by aatxe** [comment]
Okay, sounds good. It sounds to me like there should also be a save function then. Do you agree?

**Comment by zetok** [comment]
Yeah, there probably should be one.

**Comment by aatxe** [comment]
Do you want to add that to this pull request and squash?

**Comment by zetok** [comment]
Sorry, but no.

Generally, I dislike contributing to projects not licensed under GPL - though if I make some changes locally that seem to be useful upstream, and contributing them upstream isn't painful, I send improvements.

In this case, I got what I wanted, and I think that having change upstream would also help other people, thus this PR `:)`

**Comment by aatxe** [comment]
Okay, sure.

**Pull request merged**
