### PR TITLE
Update conn.rs

### PR DESCRIPTION
**Pull request by rundrop1**
Updated to Tlsv1_2 and changed deprecated SSlStream::new to SslStream::connect_generic

### CODE REVIEW

**Comment by aatxe** [comment]
I'm confused. Why did you change the name of the feature everywhere?

**Comment by rundrop1** [comment]
https://sfackler.github.io/rust-openssl/doc/v0.6.7/openssl/ssl/enum.SslMethod.html

I wanted to use Tlsv1_2, I had errors when I attempted to change connect_generic from Tlsv1 to Tlsv1_2 and changing the feature name fixed it.

**Comment by aatxe** [comment]
The Tlsv1_2 feature doesn't exist in my library. Have you actually tried using this? I'm fairly certain it'll always panic with the SSL not supported error. If you check a [newer version](http://sfackler.github.io/rust-openssl/doc/v0.7.0/openssl/ssl/enum.SslMethod.html) of the OpenSSL docs, you'll see this:

```
Support TLSv1.1 protocol, requires the tlsv1_1 feature.
```

So, the OpenSSL dependency needs to have that feature set.

**Comment by aatxe** [comment]
Here's the result of running the simple SSL example on your fork:

```
     Running `target/debug/examples/simple_ssl`
thread '<main>' panicked at 'Cannot connect to irc.fyrechat.net:6697 over SSL without compiling with SSL support.', src/client/conn.rs:62
Process didn't exit successfully: `target/debug/examples/simple_ssl` (exit code: 101)
```

**Comment by rundrop1** [comment]
Right on, sorry I've goofed here pretty badly.

**Comment by aatxe** [comment]
No worries. I'll add the tlsv1_2 feature requirement and enable that. Did you want this because you were having issues connecting to some server without it?

**Comment by aatxe** [comment]
Actually, it seems that TLSv1.2 is incompatible with most IRCds.

**Comment by rundrop1** [comment]
Yeah I really goofed here. Got carried away when I was trying to fix the ::new(), sorry. Thanks for fixing the deprecated function.

**Pull request closed without merging**
