### PR TITLE
Upgrade native-tls and tokio-tls to 0.2

### PR DESCRIPTION
**Pull request by Jokler**
This should fix builds for systems with OpenSSL 1.1.1.

[OpenSSL Issue](https://github.com/sfackler/rust-openssl/issues/994)

### CODE REVIEW

**Comment by aatxe** [comment]
Looks good to me! Thanks!

**Comment by polyzen** [comment]
Could a new release be made including this fix?

**Comment by nuxeh** [comment]
If there was a new release, i'd update the crate in my project, thanks for the heads up, @polyzen

**Comment by aatxe** [comment]
Thanks for the poke. 0.13.6 is now available. 😄

**Pull request merged**
