### PR TITLE
Clean up tokio-core

### PR DESCRIPTION
**Pull request by DoumanAsh**

### CODE REVIEW

**Comment by DoumanAsh** [comment]
@aatxe I wonder if I should PR against `develop` branch rather than `0.14`?

**Comment by aatxe** [comment]
This is a breaking API change. So, `0.14` is the right place. Thanks!

**Comment by aatxe** [comment]
@DoumanAsh Looks like one of the doctests (the example for `IrcClient::new_future`) is failing for some reason. I think because it's still being passed the (now non-existent) handle in the example.

**Comment by DoumanAsh** [comment]
Opps sorry, corrected it

**Comment by aatxe** [comment]
Okay, everything looks good now! Thanks again! 🍻

**Pull request merged**
